services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    restart: always

  backend:
    build:
      context: ./backend/GameStudy/
    container_name: backend_c
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      db-url: jdbc:postgresql://db:5432/postgres
      db-username: postgres
      db-password: qwerty

  frontend:
    container_name: frontend_c
    depends_on:
      - backend
    build:
      context: ./frontend/gamestudy/
    ports:
      - 3000:3000
    restart: always
    stdin_open: true
    tty: true


  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
      - db